package mcheli.plane;

import java.util.ArrayList;
import java.util.List;
import mcheli.MCH_Config;
import mcheli.MCH_Lib;
import mcheli.MCH_MOD;
import mcheli.aircraft.MCH_BaseVehicleInfo;
import mcheli.plane.MCP_ItemPlane;
import net.minecraft.item.Item;

public class MCP_PlaneInfo extends MCH_BaseVehicleInfo {

   public MCP_ItemPlane item = null;
   public List nozzles = new ArrayList();
   public List rotorList = new ArrayList();
   public List wingList = new ArrayList();
   public boolean isEnableVtol = false;
   public boolean isDefaultVtol;
   public float vtolYaw = 0.3F;
   public float vtolPitch = 0.2F;
   public boolean isEnableAutoPilot = false;
   public boolean isVariableSweepWing = false;
   public float sweepWingSpeed;
   /** Baseline airborne drag applied every tick. */
   public float baseDrag = 0.0015F;
   /** Extra drag generated by banked, high-load turns. */
   public float inducedDrag = 0.006F;
   /** Extra drag generated while the aircraft controls are moving. */
   public float controlSurfaceDrag = 0.0025F;
   /** Horizontal speed traded away while climbing. */
   public float climbEnergyLoss = 0.006F;
   /** Horizontal speed recovered while descending. */
   public float diveEnergyGain = 0.008F;
   /** Sustainable full-power speed in level flight; zero uses Speed. */
   public float maxLevelSpeed = 0.0F;
   /** Additional drag at closed throttle. */
   public float idleDrag = 0.004F;

   // Fixed-wing aerodynamic/flight-model tuning. These values are intentionally plane-only.
   /** Control torque applied around each local plane axis. */
   public float pitchTorque = 0.35F;
   public float rollTorque = 0.35F;
   public float yawTorque = 0.35F;
   /** Angular drag applied to each local plane axis. */
   public float pitchDamping = 0.35F;
   public float rollDamping = 0.35F;
   public float yawDamping = 0.35F;
   /** Scales resistance to angular acceleration without changing eventual control authority. */
   public float inertiaMultiplier = 1.0F;
   /** Legacy maximum engine-output increase per tick. */
   public float throttleAcceleration = 0.02F;
   /** Legacy maximum engine-output decrease per tick. */
   public float engineDrag = 0.015F;
   /** Non-linear pilot-throttle to thrust curve used by the new flight model. */
   public float newFlightThrottleResponse = 1.0F;
   /** Pilot throttle increase/decrease rates used only by the new flight model. */
   public float newFlightThrottleChangeRateUp = 0.006F;
   public float newFlightThrottleChangeRateDown = 0.008F;
   /** Minimum effective engine power at zero commanded throttle. */
   public float newFlightIdleThrottle = 0.08F;
   /** Closed-throttle aerodynamic braking used by the new flight model. */
   public float newFlightEngineBrakeDrag = 0.0035F;
   /** Fraction of legacy throttle-coupled lift retained at idle. */
   public float newFlightLowThrottleLiftRetention = 0.82F;
   /** Maximum fraction of control authority lost at idle throttle. */
   public float newFlightThrottleControlAuthorityScale = 0.18F;
   /** Show the normalized 0-100% throttle readout to pilots using the new flight model. */
   public boolean newFlightThrottleHudDisplay = true;
   /** Enables the new-flight-only combat-flap toggle. */
   public boolean newFlightCombatFlaps = false;
   public float newFlightCombatFlapLift = 0.16F;
   public float newFlightCombatFlapDrag = 0.009F;
   public float newFlightCombatFlapControl = 0.14F;
   public float newFlightCombatFlapOverspeed = 0.82F;
   /** Absolute airspeed below which a fixed-wing plane can enter a stall. Zero derives it from StallSpeedFactor. */
   public float stallSpeed = 0.0F;
   /** Angle between the plane forward vector and velocity vector at which airflow separates. */
   public float criticalAoA = 18.0F;
   /** Fraction of lift removed at a fully developed stall. */
   public float stallLiftLoss = 0.65F;
   /** Scales drag generated by angle of attack. */
   public float aoaDragMultiplier = 1.5F;
   /** Strength of deterministic buffet and wing-drop motion during a stall. */
   public float stallInstability = 0.35F;
   /** Airspeed required, together with a reduced AoA, to leave a stall. Zero derives it from StallSpeed. */
   public float stallRecoverySpeed = 0.0F;
   /** Legacy fraction of configured top speed used when StallSpeed is not set. */
   public float stallSpeedFactor = 0.22F;
   /** Legacy stall response strength, retained for plane packs that already tune it. */
   public float stallStrength = 0.6F;
   /** Maximum extra horizontal speed available while a plane is diving. */
   public float diveSpeedMultiplier = 1.25F;
   /** Load factor where high-G control authority begins to fade. */
   public float maxComfortableG = 4.0F;
   /** Load factor treated as the structural limit. */
   public float maxStructuralG = 8.0F;
   /** Maximum fraction of control authority removed by excessive G. */
   public float gControlPenalty = 0.7F;
   /** Airspeed where pitch compressibility begins. Zero derives 90% of configured speed. */
   public float compressibilitySpeed = 0.0F;
   /** Maximum fraction of pitch authority removed by compressibility. */
   public float compressibilityPitchPenalty = 0.65F;
   /** Airspeed where overspeed warnings and damage begin. Zero derives 110% of configured speed. */
   public float maxSafeSpeed = 0.0F;
   /** Damage points per tick at 100% overspeed; zero leaves the damage hook disabled. */
   public float overspeedDamageRate = 0.2F;


   public Item getItem() {
      return this.item;
   }

   public MCP_PlaneInfo(String name) {
      super(name);
      this.sweepWingSpeed = super.speed;
      this.motionFactor = 0.975F;
   }

   public float getDefaultRotorSpeed() {
      return 47.94F;
   }

   private float getDefaultStepHeight() {
      return 0.6F;
   }

   public boolean haveNozzle() {
      return this.nozzles.size() > 0;
   }

   public boolean haveRotor() {
      return this.rotorList.size() > 0;
   }

   public boolean haveWing() {
      return this.wingList.size() > 0;
   }

   public float getMaxSpeed() {
      return 4.0F;
   }

   public int getDefaultMaxZoom() {
      return 8;
   }

   public String getDefaultHudName(int seatId) {
      return seatId <= 0?"plane":(seatId == 1?"plane":"gunner");
   }

   public boolean isValidData() throws Exception {
      if(this.haveHatch() && this.haveWing()) {
         this.wingList.clear();
         super.hatchList.clear();
      }

      double var10001 = (double)super.speed;
      MCH_Config var10002 = MCH_MOD.config;
      super.speed = (float)(var10001 * MCH_Config.AllPlaneSpeed.prmDouble);
      var10001 = (double)this.sweepWingSpeed;
      var10002 = MCH_MOD.config;
      this.sweepWingSpeed = (float)(var10001 * MCH_Config.AllPlaneSpeed.prmDouble);
      if(this.maxLevelSpeed > 0.0F) {
         this.maxLevelSpeed = (float)((double)this.maxLevelSpeed * MCH_Config.AllPlaneSpeed.prmDouble);
      }
      this.scaleSpeedThresholds(MCH_Config.AllPlaneSpeed.prmDouble);
      this.warnSuspiciousFlightModelValues();
      return super.isValidData();
   }



   private void warnSuspiciousFlightModelValues() {
      if(this.maxStructuralG < this.maxComfortableG) {
         MCH_Lib.Log("[MCHeli][Config][Plane:%s] MaxStructuralG %.2f is below MaxComfortableG %.2f; high-G authority will begin and end at nearly the same load.",
               new Object[]{super.name, Float.valueOf(this.maxStructuralG), Float.valueOf(this.maxComfortableG)});
      }
      if(this.maxSafeSpeed > 0.0F && this.compressibilitySpeed > 0.0F && this.maxSafeSpeed <= this.compressibilitySpeed) {
         MCH_Lib.Log("[MCHeli][Config][Plane:%s] MaxSafeSpeed %.3f is not above CompressibilitySpeed %.3f; compressibility will reach full penalty immediately at overspeed.",
               new Object[]{super.name, Float.valueOf(this.maxSafeSpeed), Float.valueOf(this.compressibilitySpeed)});
      }
      if(this.stallRecoverySpeed > 0.0F && this.stallSpeed > 0.0F && this.stallRecoverySpeed < this.stallSpeed) {
         MCH_Lib.Log("[MCHeli][Config][Plane:%s] StallRecoverySpeed %.3f is below StallSpeed %.3f; stalls may clear while still below the entry threshold.",
               new Object[]{super.name, Float.valueOf(this.stallRecoverySpeed), Float.valueOf(this.stallSpeed)});
      }
   }

   private void scaleSpeedThresholds(double speedScale) {
      if(this.stallSpeed > 0.0F) {
         this.stallSpeed = (float)((double)this.stallSpeed * speedScale);
      }
      if(this.stallRecoverySpeed > 0.0F) {
         this.stallRecoverySpeed = (float)((double)this.stallRecoverySpeed * speedScale);
      }
      if(this.compressibilitySpeed > 0.0F) {
         this.compressibilitySpeed = (float)((double)this.compressibilitySpeed * speedScale);
      }
      if(this.maxSafeSpeed > 0.0F) {
         this.maxSafeSpeed = (float)((double)this.maxSafeSpeed * speedScale);
      }
   }

   public void loadItemData(String item, String data) {
      super.loadItemData(item, data);
      String[] s;
      if(item.compareTo("addpartrotor") == 0) {
         s = data.split("\\s*,\\s*");
         if(s.length >= 6) {
            float n = s.length >= 7?this.toFloat(s[6], -180.0F, 180.0F) / 90.0F:1.0F;
            MCP_PlaneInfo.Rotor n1 = new MCP_PlaneInfo.Rotor(this.toFloat(s[0]), this.toFloat(s[1]), this.toFloat(s[2]), this.toFloat(s[3]), this.toFloat(s[4]), this.toFloat(s[5]), n, "rotor" + this.rotorList.size());
            this.rotorList.add(n1);
         }
      } else if(item.compareTo("addblade") == 0) {
         int s1 = this.rotorList.size() - 1;
         MCP_PlaneInfo.Rotor n2 = this.rotorList.size() > 0?(MCP_PlaneInfo.Rotor)this.rotorList.get(s1):null;
         if(n2 != null) {
            String[] n4 = data.split("\\s*,\\s*");
            if(n4.length == 8) {
               MCP_PlaneInfo.Blade b = new MCP_PlaneInfo.Blade(this.toInt(n4[0]), this.toInt(n4[1]), this.toFloat(n4[2]), this.toFloat(n4[3]), this.toFloat(n4[4]), this.toFloat(n4[5]), this.toFloat(n4[6]), this.toFloat(n4[7]), "blade" + s1);
               n2.blades.add(b);
            }
         }
      } else {
         MCP_PlaneInfo.Wing n3;
         if(item.compareTo("addpartwing") == 0) {
            s = data.split("\\s*,\\s*");
            if(s.length == 7) {
               n3 = new MCP_PlaneInfo.Wing(this.toFloat(s[0]), this.toFloat(s[1]), this.toFloat(s[2]), this.toFloat(s[3]), this.toFloat(s[4]), this.toFloat(s[5]), this.toFloat(s[6]), "wing" + this.wingList.size());
               this.wingList.add(n3);
            }
         } else if(item.equalsIgnoreCase("AddPartPylon")) {
            s = data.split("\\s*,\\s*");
            if(s.length >= 7 && this.wingList.size() > 0) {
               n3 = (MCP_PlaneInfo.Wing)this.wingList.get(this.wingList.size() - 1);
               if(n3.pylonList == null) {
                  n3.pylonList = new ArrayList();
               }

               MCP_PlaneInfo.Pylon n6 = new MCP_PlaneInfo.Pylon(this.toFloat(s[0]), this.toFloat(s[1]), this.toFloat(s[2]), this.toFloat(s[3]), this.toFloat(s[4]), this.toFloat(s[5]), this.toFloat(s[6]), n3.modelName + "_pylon" + n3.pylonList.size());
               n3.pylonList.add(n6);
            }
         } else if(item.compareTo("addpartnozzle") == 0) {
            s = data.split("\\s*,\\s*");
            if(s.length == 6) {
               MCH_BaseVehicleInfo.DrawnPart n5 = new MCH_BaseVehicleInfo.DrawnPart(this.toFloat(s[0]), this.toFloat(s[1]), this.toFloat(s[2]), this.toFloat(s[3]), this.toFloat(s[4]), this.toFloat(s[5]), "nozzle" + this.nozzles.size());
               this.nozzles.add(n5);
            }
         } else if(item.compareTo("variablesweepwing") == 0) {
            this.isVariableSweepWing = this.toBool(data);
         } else if(item.compareTo("sweepwingspeed") == 0) {
            this.sweepWingSpeed = this.toFloat(data, 0.0F, 5.0F);
         } else if(item.compareTo("enablevtol") == 0) {
            this.isEnableVtol = this.toBool(data);
         } else if(item.compareTo("defaultvtol") == 0) {
            this.isDefaultVtol = this.toBool(data);
         } else if(item.compareTo("vtolyaw") == 0) {
            this.vtolYaw = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.compareTo("vtolpitch") == 0) {
            this.vtolPitch = this.toFloat(data, 0.01F, 1.0F);
         } else if(item.compareTo("enableautopilot") == 0) {
            this.isEnableAutoPilot = this.toBool(data);
         } else if(item.equalsIgnoreCase("BaseDrag")) {
            this.baseDrag = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("InducedDrag")) {
            this.inducedDrag = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("ControlSurfaceDrag")) {
            this.controlSurfaceDrag = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("ClimbEnergyLoss")) {
            this.climbEnergyLoss = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("DiveEnergyGain")) {
            this.diveEnergyGain = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("MaxLevelSpeed")) {
            this.maxLevelSpeed = this.toFloat(data, 0.0F, this.getMaxSpeed());
         } else if(item.equalsIgnoreCase("IdleDrag")) {
            this.idleDrag = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("PitchTorque")) {
            this.pitchTorque = this.toFloat(data, 0.0F, 100.0F);
         } else if(item.equalsIgnoreCase("RollTorque")) {
            this.rollTorque = this.toFloat(data, 0.0F, 100.0F);
         } else if(item.equalsIgnoreCase("YawTorque")) {
            this.yawTorque = this.toFloat(data, 0.0F, 100.0F);
         } else if(item.equalsIgnoreCase("PitchDamping")) {
            this.pitchDamping = this.toFloat(data, 0.0F, 100.0F);
         } else if(item.equalsIgnoreCase("RollDamping")) {
            this.rollDamping = this.toFloat(data, 0.0F, 100.0F);
         } else if(item.equalsIgnoreCase("YawDamping")) {
            this.yawDamping = this.toFloat(data, 0.0F, 100.0F);
         } else if(item.equalsIgnoreCase("Mass") || item.equalsIgnoreCase("InertiaMultiplier")) {
            this.inertiaMultiplier = this.toFloat(data, 0.05F, 100.0F);
         } else if(item.equalsIgnoreCase("ThrottleAcceleration")) {
            this.throttleAcceleration = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("EngineDrag")) {
            this.engineDrag = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("NewFlightThrottleResponse")) {
            this.newFlightThrottleResponse = this.toFloat(data, 0.1F, 4.0F);
         } else if(item.equalsIgnoreCase("NewFlightThrottleChangeRateUp")) {
            this.newFlightThrottleChangeRateUp = this.toFloat(data, 0.0F, 0.1F);
         } else if(item.equalsIgnoreCase("NewFlightThrottleChangeRateDown")) {
            this.newFlightThrottleChangeRateDown = this.toFloat(data, 0.0F, 0.1F);
         } else if(item.equalsIgnoreCase("NewFlightIdleThrottle")) {
            this.newFlightIdleThrottle = this.toFloat(data, 0.0F, 0.35F);
         } else if(item.equalsIgnoreCase("NewFlightEngineBrakeDrag")) {
            this.newFlightEngineBrakeDrag = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("NewFlightLowThrottleLiftRetention")) {
            this.newFlightLowThrottleLiftRetention = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("NewFlightThrottleControlAuthorityScale")) {
            this.newFlightThrottleControlAuthorityScale = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("NewFlightThrottleHudDisplay")) {
            this.newFlightThrottleHudDisplay = this.toBool(data);
         } else if(item.equalsIgnoreCase("NewFlightCombatFlaps")) {
            this.newFlightCombatFlaps = this.toBool(data);
         } else if(item.equalsIgnoreCase("NewFlightCombatFlapLift")) {
            this.newFlightCombatFlapLift = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("NewFlightCombatFlapDrag")) {
            this.newFlightCombatFlapDrag = this.toFloat(data, 0.0F, 0.25F);
         } else if(item.equalsIgnoreCase("NewFlightCombatFlapControl")) {
            this.newFlightCombatFlapControl = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("NewFlightCombatFlapOverspeed")) {
            this.newFlightCombatFlapOverspeed = this.toFloat(data, 0.1F, 1.0F);
         } else if(item.equalsIgnoreCase("StallSpeed")) {
            this.stallSpeed = this.toFloat(data, 0.0F, 10.0F);
         } else if(item.equalsIgnoreCase("CriticalAoA")) {
            this.criticalAoA = this.toFloat(data, 1.0F, 90.0F);
         } else if(item.equalsIgnoreCase("StallLiftLoss")) {
            this.stallLiftLoss = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("AoADragMultiplier")) {
            this.aoaDragMultiplier = this.toFloat(data, 0.0F, 10.0F);
         } else if(item.equalsIgnoreCase("StallInstability")) {
            this.stallInstability = this.toFloat(data, 0.0F, 5.0F);
         } else if(item.equalsIgnoreCase("StallRecoverySpeed")) {
            this.stallRecoverySpeed = this.toFloat(data, 0.0F, 10.0F);
         } else if(item.equalsIgnoreCase("StallSpeedFactor")) {
            this.stallSpeedFactor = this.toFloat(data, 0.0F, 0.95F);
         } else if(item.equalsIgnoreCase("StallStrength")) {
            this.stallStrength = this.toFloat(data, 0.0F, 4.0F);
         } else if(item.equalsIgnoreCase("DiveSpeedMultiplier")) {
            this.diveSpeedMultiplier = this.toFloat(data, 1.0F, 2.0F);
         } else if(item.equalsIgnoreCase("MaxComfortableG")) {
            this.maxComfortableG = this.toFloat(data, 1.0F, 30.0F);
         } else if(item.equalsIgnoreCase("MaxStructuralG")) {
            this.maxStructuralG = this.toFloat(data, 1.0F, 50.0F);
         } else if(item.equalsIgnoreCase("GControlPenalty")) {
            this.gControlPenalty = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("CompressibilitySpeed")) {
            this.compressibilitySpeed = this.toFloat(data, 0.0F, 10.0F);
         } else if(item.equalsIgnoreCase("CompressibilityPitchPenalty")) {
            this.compressibilityPitchPenalty = this.toFloat(data, 0.0F, 1.0F);
         } else if(item.equalsIgnoreCase("MaxSafeSpeed")) {
            this.maxSafeSpeed = this.toFloat(data, 0.0F, 10.0F);
         } else if(item.equalsIgnoreCase("OverspeedDamageRate")) {
            this.overspeedDamageRate = this.toFloat(data, 0.0F, 100.0F);
         }
      }
      MCH_BaseVehicleInfo.allBaseVehicleInfo.put(name, this);
   }

   public String getDirectoryName() {
      return "planes";
   }

   public String getKindName() {
      return "plane";
   }

   public void preReload() {
      super.preReload();
      this.nozzles.clear();
      this.rotorList.clear();
      this.wingList.clear();
   }

   public void postReload() {
      MCH_MOD.proxy.registerModelsPlane(super.name, true);
   }

   public class Rotor extends MCH_BaseVehicleInfo.DrawnPart {

      public List blades = new ArrayList();
      public final float maxRotFactor;


      public Rotor(float x, float y, float z, float rx, float ry, float rz, float mrf, String model) {
         super(x, y, z, rx, ry, rz, model);
         this.maxRotFactor = mrf;
      }
   }

   public class Pylon extends MCH_BaseVehicleInfo.DrawnPart {

      public final float maxRotFactor;
      public final float maxRot;


      public Pylon(float px, float py, float pz, float rx, float ry, float rz, float mr, String name) {
         super(px, py, pz, rx, ry, rz, name);
         this.maxRot = mr;
         this.maxRotFactor = this.maxRot / 90.0F;
      }
   }

   public class Blade extends MCH_BaseVehicleInfo.DrawnPart {

      public final int numBlade;
      public final int rotBlade;


      public Blade(int num, int r, float px, float py, float pz, float rx, float ry, float rz, String name) {
         super(px, py, pz, rx, ry, rz, name);
         this.numBlade = num;
         this.rotBlade = r;
      }
   }

   public class Wing extends MCH_BaseVehicleInfo.DrawnPart {

      public final float maxRotFactor;
      public final float maxRot;
      public List pylonList;


      public Wing(float px, float py, float pz, float rx, float ry, float rz, float mr, String name) {
         super(px, py, pz, rx, ry, rz, name);
         this.maxRot = mr;
         this.maxRotFactor = this.maxRot / 90.0F;
         this.pylonList = null;
      }
   }
}
